server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # If a file isn't found, fall back to index.html for React routing
        try_files $uri $uri/ /index.html;
    }
}